Project: Private Events
crappypapa/private-events pull request #1
Opened 2021-05-06 11:25 UTC by crappypapa

In this project, we used ActiveRecord’s associations to model the workings of a private event website.
We created associations between our models so as to satisfy the following conditions

- A user can create events. 
- A user can attend many events. 
- An event can be attended by many users.

We have done this project with little regard for styling as we would like to be certain the app meets requirements before expending energy on styling.

2021-05-06 12:29 UTC, mimipeshy commented
## STATUS: CHANGES REQUESTED 🔴 ♻️ 

Hello team @crappypapa and @CollinsTatang 👋🏾 👋🏾  great job on working on this milestone

### Highlights

- You have followed the correct git-flow ✔️ 
- Your linter checks do not raise any error ✔️ 
-  A user can create events and attend events ✔️ 

### To Improve

- [ ] Check inline comments on what can be improved 😄 


That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu
_If you have any questions, kindly leave a comment here and tag my name @mimipeshy and I will be glad to help_

2021-05-06 12:32 UTC, mimipeshy commented on app/controllers/events_controller.rb
> +
- [ ]  Event #index should list past events, i.e. `@past_events = Event.previous_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from  [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- [ ] Event #index should list upcoming events, i.e. `@upcoming_events = Event.upcoming_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2021-05-06 12:33 UTC, mimipeshy commented on app/controllers/users_controller.rb
> +
##### UsersController

###### `show` action

* [ ] lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2021-05-06 12:38 UTC, mimipeshy commented on config/routes.rb
> +  end
- [ ] Lets also ensure that  routes are only for used actions, i.e. `resources :events, only: [:new, :create, :show, :index]`

2021-05-06 15:18 UTC, rukundoeric requested changes
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - The codebasee is clean. 💯
  - The project follows Git flow. 💯
  - All feedback from the previous review are well implemented. 💯 

- ### To Improve
  - [ ] [MANDATORY] Views should be logic-free. kindly remove all logic related code from views, especialy `if-else` statements.
  - [ ] [MANDATORY]In RESTFUL APIs we don't need to overly complicate/customize route names:
       - So user signup is simply included here: resources :users
       - login in is simply: resources :sessions, only: [:create]
       - And logout is simply: resources :sessions, only: [:create]


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

2021-05-06 15:18 UTC, rukundoeric commented on app/views/events/_form.html.erb
> +  <% end %>
Move this logic to helpers

2021-05-06 15:18 UTC, rukundoeric commented on app/views/events/show.html.erb
> +<% end %>
Move this logic to helpers

2021-05-06 15:18 UTC, rukundoeric commented on app/views/events/show.html.erb
> +    <% end %>
Move this logic to helpers

2021-05-06 15:18 UTC, rukundoeric commented on app/views/layouts/application.html.erb
> +      <div class="notification">
Move this logic to helpers

2021-05-06 15:18 UTC, rukundoeric commented on app/views/layouts/application.html.erb
> +      <div class="notification">
Move this logic to helpers

2021-05-06 15:18 UTC, rukundoeric commented on app/views/layouts/application.html.erb
> +                  <%= link_to 'Sign In', login_path, class: "btn" %>
Move this logic to helpers

2021-05-06 15:18 UTC, rukundoeric commented on app/views/users/_form.html.erb
> +        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
Move this logic to helpers

2021-05-06 15:18 UTC, rukundoeric commented on config/routes.rb
> +  get 'logout' => 'sessions#destroy', as: 'logout'
- In RESTFUL APIs we don't need to overly complicate/customize route names:
     - So user signup is simply included here:  `resources :users`
     - login in is simply: `resources :sessions, only: [:create]`
     - And logout is simply: `resources :sessions, only: [:create]`

2021-05-07 05:37 UTC, crappypapa commented
I have removed all logic from views as requested and I have refactored the session routes to the best of my current abilities.

2021-05-07 05:53 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @crappypapa &  @CollinsTatang 

Good job on implementing the suggested changes. Well done. 

- In readme file setup section, you have missed the `rails db:migrate` command to populate the database. Please write this step before merging.

**You may close this Pull Request and merge the changes**
 
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏

Code review by **Dipesh Kumar**
(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
[Dipesh Kumar](https://deeptwist.tk) | [Twitter](https://twitter.com/97deepeshkumar)

2021-05-07 05:56 UTC, crappypapa commented
@Dipeshtwis  I will add the required command to the readme as suggested. Thank you.

2021-05-07 05:58 UTC, merged